name: e_track14_mobile
description: Draft Flutter app for E-Track14 (Auth, Attendance, Student Scan, Leave, Settings)
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  graphql_flutter: ^5.2.0
  mobile_scanner: ^3.5.6
  geolocator: ^11.0.0
  permission_handler: ^11.3.1
  image_picker: ^1.1.0
  camera: ^0.11.0+2
  dio: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

